In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/drive/MyDrive/healthcare_dataset.csv")
print(df)

                    Name  Age  Gender Blood Type Medical Condition  \
0          Bobby JacksOn   30    Male         B-            Cancer
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
3           andrEw waTtS   28  Female         O+          Diabetes
4          adrIENNE bEll   43  Female        AB+            Cancer
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
0            2024-01-31     Matthew Smith               Sons and Miller
1            2019-08-20   Samantha Davies                       Kim Inc
2            2022-09-22  Tiffany Mitchell                      Cook PLC
3            2020-11-18       Kevin Wells    Hernandez Rogers and Vang,
4            2022-09-19    Kathleen Hanna                   White-White
...                 ...               ...                           ...
55495        2020-08-16     Joshua Jarvis                Jones-Thompson
55496        2020-01-23   Taylor Sullivan                  Tucker-Moyer
55497        2020-07-13    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        2019-05-25    Kimberly Curry      Jackson Todd and Castro,
55499        2024-04-02     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
0             Blue Cross    18856.281306          328         Urgent
1               Medicare    33643.327287          265      Emergency
2                  Aetna    27955.096079          205      Emergency
3               Medicare    37909.782410          450       Elective
4                  Aetna    14238.317814          458         Urgent
...                  ...             ...          ...            ...
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797307          316       Elective
55497   UnitedHealthcare    27620.764717          347         Urgent
55498           Medicare    32451.092358          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date   Medication  Test Results
0         2024-02-02  Paracetamol        Normal
1         2019-08-26    Ibuprofen  Inconclusive
2         2022-10-07      Aspirin        Normal
3         2020-12-18    Ibuprofen      Abnormal
4         2022-10-09   Penicillin      Abnormal
...              ...          ...           ...
55495     2020-09-15   Penicillin      Abnormal
55496     2020-02-01      Aspirin        Normal
55497     2020-08-10    Ibuprofen      Abnormal
55498     2019-05-31    Ibuprofen      Abnormal
55499     2024-04-29    Ibuprofen      Abnormal

[55500 rows x 15 columns]

In [ ]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [ ]:
df.tail()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [ ]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [ ]:
df.isnull()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [ ]:
university = {
    "student": [
        "Ali", "Ahmed", "Sara", "Sana", "Saba", "Daniyal", "Saima",
        "Shabnam", "Faria", "Badar", "Lubna", "Shamraiz", "Fareeha", "Sumbal"
    ],

    "department": [
        "AI", "CS", "Cyber Security", "Intelligent System",
        "Electrical Engineering", "Mechanical Engineering",
        "Civil Engineering", "Emerging Allied Health Technologies",
        "Health Professional Technologies", "Chemistry", "Physics",
        "Economics", "Audiology", "Optometry"
    ],

    "sap_id": [
        "1", "2", "3", "4", "5", "6", "7",
        "8", "9", "10", "11", "12", "13", "14"
    ],

    "lecturer": [
        "Sir Usman", "Sir Khalid", "Prof Abid", "Prof Shahid",
        "Prof Asia", "Prof Iqbal", "Sir Ali", "Mam Nimra",
        "Sir Moeez", "Mam Hifza", "Mam Fizza", "Mam Mennal",
        "Mam Shazia", "Mam Ayesha"
    ],

    "section": [
        "A", "B", "C", "A", "F", "C", "G",
        "A", "B", "D", "A", "C", "I", "B"
    ],

    "degree": [
        "BSAI", "BSCS", "BS Cyber Security", "BS Intelligent Systems",
        "BS Electrical Engineering", "BS Mechanical Engineering",
        "BS Civil Engineering", "BS Allied Health Technologies",
        "BS Health Technologies", "BS Chemistry", "BS Physics",
        "BS Economics", "BS Audiology", "BS Optometry"
    ],

    "father_name": [
        "Muhammad Ashraf", "Muhammad Iqbal", "Abdul Rehman",
        "Muhammad Arif", "Muhammad Yousaf", "Ghulam Mustafa",
        "Muhammad Aslam", "Muhammad Akram", "Muhammad Hanif",
        "Muhammad Rafiq", "Abdul Sattar", "Muhammad Bashir",
        "Muhammad Tariq", "Muhammad Saleem"
    ],

    "phone_number": [
        "03001234567", "03011234567", "03021234567",
        "03031234567", "03041234567", "03051234567",
        "03061234567", "03071234567", "03081234567",
        "03091234567", "03101234567", "03111234567",
        "03121234567", "03131234567"
    ],

    "cnic": [
        "35202-1234567-1", "35202-2345678-2",
        "35202-3456789-3", "35202-4567890-4",
        "35202-5678901-5", "35202-6789012-6",
        "35202-7890123-7", "35202-8901234-8",
        "35202-9012345-9", "35202-1122334-0",
        "35202-2233445-1", "35202-3344556-2",
        "35202-4455667-3", "35202-5566778-4"
    ],

    "cgpa": [
        2.45, 2.78, 3.10, 3.25, 3.40, 3.55, 3.68,
        3.72, 3.80, 3.91, 2.95, 3.15, 3.50, 3.99
    ],

    "disability": [
        "None", "None", "Physical", "None", "Visual",
        "None", "Hearing", "None", "None", "Physical",
        "None", "Visual", "None", "None"
    ]
}

In [ ]:
a = pd.DataFrame(university)
a.to_csv("university.csv",index=False)
print(a)

     student                           department sap_id     lecturer section  \
0        Ali                                   AI      1    Sir Usman       A
1      Ahmed                                   CS      2   Sir Khalid       B
2       Sara                       Cyber Security      3    Prof Abid       C
3       Sana                   Intelligent System      4  Prof Shahid       A
4       Saba               Electrical Engineering      5    Prof Asia       F
5    Daniyal               Mechanical Engineering      6   Prof Iqbal       C
6      Saima                    Civil Engineering      7      Sir Ali       G
7    Shabnam  Emerging Allied Health Technologies      8    Mam Nimra       A
8      Faria     Health Professional Technologies      9    Sir Moeez       B
9      Badar                            Chemistry     10    Mam Hifza       D
10     Lubna                              Physics     11    Mam Fizza       A
11  Shamraiz                            Economics     12   Mam Mennal       C
12   Fareeha                            Audiology     13   Mam Shazia       I
13    Sumbal                            Optometry     14   Mam Ayesha       B

                           degree      father_name phone_number  \
0                            BSAI  Muhammad Ashraf  03001234567
1                            BSCS   Muhammad Iqbal  03011234567
2               BS Cyber Security     Abdul Rehman  03021234567
3          BS Intelligent Systems    Muhammad Arif  03031234567
4       BS Electrical Engineering  Muhammad Yousaf  03041234567
5       BS Mechanical Engineering   Ghulam Mustafa  03051234567
6            BS Civil Engineering   Muhammad Aslam  03061234567
7   BS Allied Health Technologies   Muhammad Akram  03071234567
8          BS Health Technologies   Muhammad Hanif  03081234567
9                    BS Chemistry   Muhammad Rafiq  03091234567
10                     BS Physics     Abdul Sattar  03101234567
11                   BS Economics  Muhammad Bashir  03111234567
12                   BS Audiology   Muhammad Tariq  03121234567
13                   BS Optometry  Muhammad Saleem  03131234567

               cnic  cgpa disability
0   35202-1234567-1  2.45       None
1   35202-2345678-2  2.78       None
2   35202-3456789-3  3.10   Physical
3   35202-4567890-4  3.25       None
4   35202-5678901-5  3.40     Visual
5   35202-6789012-6  3.55       None
6   35202-7890123-7  3.68    Hearing
7   35202-8901234-8  3.72       None
8   35202-9012345-9  3.80       None
9   35202-1122334-0  3.91   Physical
10  35202-2233445-1  2.95       None
11  35202-3344556-2  3.15     Visual
12  35202-4455667-3  3.50       None
13  35202-5566778-4  3.99       None

In [ ]:
pd.read_csv("/content/university.csv")

,student,department,sap_id,lecturer,section,degree,father_name,phone_number,cnic,cgpa,disability
0,Ali,AI,1,Sir Usman,A,BSAI,Muhammad Ashraf,3001234567,35202-1234567-1,2.45,NaN
1,Ahmed,CS,2,Sir Khalid,B,BSCS,Muhammad Iqbal,3011234567,35202-2345678-2,2.78,NaN
2,Sara,Cyber Security,3,Prof Abid,C,BS Cyber Security,Abdul Rehman,3021234567,35202-3456789-3,3.10,Physical
3,Sana,Intelligent System,4,Prof Shahid,A,BS Intelligent Systems,Muhammad Arif,3031234567,35202-4567890-4,3.25,NaN
4,Saba,Electrical Engineering,5,Prof Asia,F,BS Electrical Engineering,Muhammad Yousaf,3041234567,35202-5678901-5,3.40,Visual
5,Daniyal,Mechanical Engineering,6,Prof Iqbal,C,BS Mechanical Engineering,Ghulam Mustafa,3051234567,35202-6789012-6,3.55,NaN
6,Saima,Civil Engineering,7,Sir Ali,G,BS Civil Engineering,Muhammad Aslam,3061234567,35202-7890123-7,3.68,Hearing
7,Shabnam,Emerging Allied Health Technologies,8,Mam Nimra,A,BS Allied Health Technologies,Muhammad Akram,3071234567,35202-8901234-8,3.72,NaN
8,Faria,Health Professional Technologies,9,Sir Moeez,B,BS Health Technologies,Muhammad Hanif,3081234567,35202-9012345-9,3.80,NaN
9,Badar,Chemistry,10,Mam Hifza,D,BS Chemistry,Muhammad Rafiq,3091234567,35202-1122334-0,3.91,Physical
10,Lubna,Physics,11,Mam Fizza,A,BS Physics,Abdul Sattar,3101234567,35202-2233445-1,2.95,NaN
11,Shamraiz,Economics,12,Mam Mennal,C,BS Economics,Muhammad Bashir,3111234567,35202-3344556-2,3.15,Visual
12,Fareeha,Audiology,13,Mam Shazia,I,BS Audiology,Muhammad Tariq,3121234567,35202-4455667-3,3.50,NaN
13,Sumbal,Optometry,14,Mam Ayesha,B,BS Optometry,Muhammad Saleem,3131234567,35202-5566778-4,3.99,NaN

adding a column

In [ ]:
a["fees"]=345600
print(a)

     student                           department sap_id     lecturer section  \
0        Ali                                   AI      1    Sir Usman       A
1      Ahmed                                   CS      2   Sir Khalid       B
2       Sara                       Cyber Security      3    Prof Abid       C
3       Sana                   Intelligent System      4  Prof Shahid       A
4       Saba               Electrical Engineering      5    Prof Asia       F
5    Daniyal               Mechanical Engineering      6   Prof Iqbal       C
6      Saima                    Civil Engineering      7      Sir Ali       G
7    Shabnam  Emerging Allied Health Technologies      8    Mam Nimra       A
8      Faria     Health Professional Technologies      9    Sir Moeez       B
9      Badar                            Chemistry     10    Mam Hifza       D
10     Lubna                              Physics     11    Mam Fizza       A
11  Shamraiz                            Economics     12   Mam Mennal       C
12   Fareeha                            Audiology     13   Mam Shazia       I
13    Sumbal                            Optometry     14   Mam Ayesha       B

                           degree      father_name phone_number  \
0                            BSAI  Muhammad Ashraf  03001234567
1                            BSCS   Muhammad Iqbal  03011234567
2               BS Cyber Security     Abdul Rehman  03021234567
3          BS Intelligent Systems    Muhammad Arif  03031234567
4       BS Electrical Engineering  Muhammad Yousaf  03041234567
5       BS Mechanical Engineering   Ghulam Mustafa  03051234567
6            BS Civil Engineering   Muhammad Aslam  03061234567
7   BS Allied Health Technologies   Muhammad Akram  03071234567
8          BS Health Technologies   Muhammad Hanif  03081234567
9                    BS Chemistry   Muhammad Rafiq  03091234567
10                     BS Physics     Abdul Sattar  03101234567
11                   BS Economics  Muhammad Bashir  03111234567
12                   BS Audiology   Muhammad Tariq  03121234567
13                   BS Optometry  Muhammad Saleem  03131234567

               cnic  cgpa disability    fees
0   35202-1234567-1  2.45       None  345600
1   35202-2345678-2  2.78       None  345600
2   35202-3456789-3  3.10   Physical  345600
3   35202-4567890-4  3.25       None  345600
4   35202-5678901-5  3.40     Visual  345600
5   35202-6789012-6  3.55       None  345600
6   35202-7890123-7  3.68    Hearing  345600
7   35202-8901234-8  3.72       None  345600
8   35202-9012345-9  3.80       None  345600
9   35202-1122334-0  3.91   Physical  345600
10  35202-2233445-1  2.95       None  345600
11  35202-3344556-2  3.15     Visual  345600
12  35202-4455667-3  3.50       None  345600
13  35202-5566778-4  3.99       None  345600

delete a column

In [ ]:
a = a.drop("department",axis=1)
print(a)

     student sap_id     lecturer section                         degree  \
0        Ali      1    Sir Usman       A                           BSAI
1      Ahmed      2   Sir Khalid       B                           BSCS
2       Sara      3    Prof Abid       C              BS Cyber Security
3       Sana      4  Prof Shahid       A         BS Intelligent Systems
4       Saba      5    Prof Asia       F      BS Electrical Engineering
5    Daniyal      6   Prof Iqbal       C      BS Mechanical Engineering
6      Saima      7      Sir Ali       G           BS Civil Engineering
7    Shabnam      8    Mam Nimra       A  BS Allied Health Technologies
8      Faria      9    Sir Moeez       B         BS Health Technologies
9      Badar     10    Mam Hifza       D                   BS Chemistry
10     Lubna     11    Mam Fizza       A                     BS Physics
11  Shamraiz     12   Mam Mennal       C                   BS Economics
12   Fareeha     13   Mam Shazia       I                   BS Audiology
13    Sumbal     14   Mam Ayesha       B                   BS Optometry

        father_name phone_number             cnic  cgpa disability    fees
0   Muhammad Ashraf  03001234567  35202-1234567-1  2.45       None  345600
1    Muhammad Iqbal  03011234567  35202-2345678-2  2.78       None  345600
2      Abdul Rehman  03021234567  35202-3456789-3  3.10   Physical  345600
3     Muhammad Arif  03031234567  35202-4567890-4  3.25       None  345600
4   Muhammad Yousaf  03041234567  35202-5678901-5  3.40     Visual  345600
5    Ghulam Mustafa  03051234567  35202-6789012-6  3.55       None  345600
6    Muhammad Aslam  03061234567  35202-7890123-7  3.68    Hearing  345600
7    Muhammad Akram  03071234567  35202-8901234-8  3.72       None  345600
8    Muhammad Hanif  03081234567  35202-9012345-9  3.80       None  345600
9    Muhammad Rafiq  03091234567  35202-1122334-0  3.91   Physical  345600
10     Abdul Sattar  03101234567  35202-2233445-1  2.95       None  345600
11  Muhammad Bashir  03111234567  35202-3344556-2  3.15     Visual  345600
12   Muhammad Tariq  03121234567  35202-4455667-3  3.50       None  345600
13  Muhammad Saleem  03131234567  35202-5566778-4  3.99       None  345600

delete a row

In [ ]:
a.drop([0,7])

,student,sap_id,lecturer,section,degree,father_name,phone_number,cnic,cgpa,disability,fees
1,Ahmed,2,Sir Khalid,B,BSCS,Muhammad Iqbal,03011234567,35202-2345678-2,2.78,None,345600
2,Sara,3,Prof Abid,C,BS Cyber Security,Abdul Rehman,03021234567,35202-3456789-3,3.10,Physical,345600
3,Sana,4,Prof Shahid,A,BS Intelligent Systems,Muhammad Arif,03031234567,35202-4567890-4,3.25,None,345600
4,Saba,5,Prof Asia,F,BS Electrical Engineering,Muhammad Yousaf,03041234567,35202-5678901-5,3.40,Visual,345600
5,Daniyal,6,Prof Iqbal,C,BS Mechanical Engineering,Ghulam Mustafa,03051234567,35202-6789012-6,3.55,None,345600
6,Saima,7,Sir Ali,G,BS Civil Engineering,Muhammad Aslam,03061234567,35202-7890123-7,3.68,Hearing,345600
8,Faria,9,Sir Moeez,B,BS Health Technologies,Muhammad Hanif,03081234567,35202-9012345-9,3.80,None,345600
9,Badar,10,Mam Hifza,D,BS Chemistry,Muhammad Rafiq,03091234567,35202-1122334-0,3.91,Physical,345600
10,Lubna,11,Mam Fizza,A,BS Physics,Abdul Sattar,03101234567,35202-2233445-1,2.95,None,345600
11,Shamraiz,12,Mam Mennal,C,BS Economics,Muhammad Bashir,03111234567,35202-3344556-2,3.15,Visual,345600
12,Fareeha,13,Mam Shazia,I,BS Audiology,Muhammad Tariq,03121234567,35202-4455667-3,3.50,None,345600
13,Sumbal,14,Mam Ayesha,B,BS Optometry,Muhammad Saleem,03131234567,35202-5566778-4,3.99,None,345600

delete  a row from 1 to 9 etc

In [ ]:
a.drop(a.index[4:9])

,student,sap_id,lecturer,section,degree,father_name,phone_number,cnic,cgpa,disability,fees
0,Ali,1,Sir Usman,A,BSAI,Muhammad Ashraf,03001234567,35202-1234567-1,2.45,None,345600
1,Ahmed,2,Sir Khalid,B,BSCS,Muhammad Iqbal,03011234567,35202-2345678-2,2.78,None,345600
2,Sara,3,Prof Abid,C,BS Cyber Security,Abdul Rehman,03021234567,35202-3456789-3,3.10,Physical,345600
3,Sana,4,Prof Shahid,A,BS Intelligent Systems,Muhammad Arif,03031234567,35202-4567890-4,3.25,None,345600
9,Badar,10,Mam Hifza,D,BS Chemistry,Muhammad Rafiq,03091234567,35202-1122334-0,3.91,Physical,345600
10,Lubna,11,Mam Fizza,A,BS Physics,Abdul Sattar,03101234567,35202-2233445-1,2.95,None,345600
11,Shamraiz,12,Mam Mennal,C,BS Economics,Muhammad Bashir,03111234567,35202-3344556-2,3.15,Visual,345600
12,Fareeha,13,Mam Shazia,I,BS Audiology,Muhammad Tariq,03121234567,35202-4455667-3,3.50,None,345600
13,Sumbal,14,Mam Ayesha,B,BS Optometry,Muhammad Saleem,03131234567,35202-5566778-4,3.99,None,345600

rename a column

In [ ]:
a.rename(columns = {"lecturer":"instructor"})

,student,sap_id,instructor,section,degree,father_name,phone_number,cnic,cgpa,disability,fees
0,Ali,1,Sir Usman,A,BSAI,Muhammad Ashraf,03001234567,35202-1234567-1,2.45,None,345600
1,Ahmed,2,Sir Khalid,B,BSCS,Muhammad Iqbal,03011234567,35202-2345678-2,2.78,None,345600
2,Sara,3,Prof Abid,C,BS Cyber Security,Abdul Rehman,03021234567,35202-3456789-3,3.10,Physical,345600
3,Sana,4,Prof Shahid,A,BS Intelligent Systems,Muhammad Arif,03031234567,35202-4567890-4,3.25,None,345600
4,Saba,5,Prof Asia,F,BS Electrical Engineering,Muhammad Yousaf,03041234567,35202-5678901-5,3.40,Visual,345600
5,Daniyal,6,Prof Iqbal,C,BS Mechanical Engineering,Ghulam Mustafa,03051234567,35202-6789012-6,3.55,None,345600
6,Saima,7,Sir Ali,G,BS Civil Engineering,Muhammad Aslam,03061234567,35202-7890123-7,3.68,Hearing,345600
7,Shabnam,8,Mam Nimra,A,BS Allied Health Technologies,Muhammad Akram,03071234567,35202-8901234-8,3.72,None,345600
8,Faria,9,Sir Moeez,B,BS Health Technologies,Muhammad Hanif,03081234567,35202-9012345-9,3.80,None,345600
9,Badar,10,Mam Hifza,D,BS Chemistry,Muhammad Rafiq,03091234567,35202-1122334-0,3.91,Physical,345600
10,Lubna,11,Mam Fizza,A,BS Physics,Abdul Sattar,03101234567,35202-2233445-1,2.95,None,345600
11,Shamraiz,12,Mam Mennal,C,BS Economics,Muhammad Bashir,03111234567,35202-3344556-2,3.15,Visual,345600
12,Fareeha,13,Mam Shazia,I,BS Audiology,Muhammad Tariq,03121234567,35202-4455667-3,3.50,None,345600
13,Sumbal,14,Mam Ayesha,B,BS Optometry,Muhammad Saleem,03131234567,35202-5566778-4,3.99,None,345600

to show one column more columns

In [ ]:
a[["student","sap_id","lecturer"]]

     student sap_id     lecturer
0        Ali      1    Sir Usman
1      Ahmed      2   Sir Khalid
2       Sara      3    Prof Abid
3       Sana      4  Prof Shahid
4       Saba      5    Prof Asia
5    Daniyal      6   Prof Iqbal
6      Saima      7      Sir Ali
7    Shabnam      8    Mam Nimra
8      Faria      9    Sir Moeez
9      Badar     10    Mam Hifza
10     Lubna     11    Mam Fizza
11  Shamraiz     12   Mam Mennal
12   Fareeha     13   Mam Shazia
13    Sumbal     14   Mam Ayesha

to show row and column by label means by name

In [ ]:
a.loc[0:2,["degree","sap_id"]]

              degree sap_id
0               BSAI      1
1               BSCS      2
2  BS Cyber Security      3

show rows and columns by index by location

In [ ]:
a.iloc[0:4,0:5]

  student sap_id     lecturer section                  degree
0     Ali      1    Sir Usman       A                    BSAI
1   Ahmed      2   Sir Khalid       B                    BSCS
2    Sara      3    Prof Abid       C       BS Cyber Security
3    Sana      4  Prof Shahid       A  BS Intelligent Systems

In [ ]:
f=([[10,20,30,40],[30,40,50,60],[90,20,40,10]])
a = pd.DataFrame(f)
print(a)

    0   1   2   3
0  10  20  30  40
1  30  40  50  60
2  90  20  40  10

to convert into row

In [ ]:
g = pd.Series([10,20,30,40])
print(g)

0    10
1    20
2    30
3    40
dtype: int64

dropna is used for where none is written then it is not print that row

In [ ]:
personal_info= {
    "name":["fizza",None,"maan"],
    "age":[19,24,None]
}
z = pd.DataFrame(personal_info)
print(z.dropna())

    name   age
0  fizza  19.0

fiilna is used for fill that row

In [ ]:
print(z.fillna(20))

    name   age
0  fizza  19.0
1  bilal  20.0
2     20  24.0

sort is used for in ascending order

In [ ]:
print(z.sort_values("name"))

    name   age
1  bilal   NaN
0  fizza  19.0
2   None  24.0

In [ ]:
print(z.groupby("name")["age"].mean())

name
bilal     NaN
fizza    19.0
Name: age, dtype: float64

groupby() . means() is used for average of something

In [ ]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR"],
    "Salary": [50000, 40000, 60000, 45000]
})

print(df.groupby("Department")["Salary"].mean())

Department
HR    42500.0
IT    55000.0
Name: Salary, dtype: float64

counts the value .value_counts

In [ ]:
print(df["Admission Type"].value_counts())

Admission Type
Elective     18655
Urgent       18576
Emergency    18269
Name: count, dtype: int64

uniquesness

In [ ]:
print(df["Admission Type"].unique())

['Urgent' 'Emergency' 'Elective']

uniquesness in counts

In [ ]:
print(df["Admission Type"].nunique())

3

concat is used for combine 2

In [ ]:
result = pd.concat([a,z])
print(result)

     student                           department sap_id     lecturer section  \
0        Ali                                   AI      1    Sir Usman       A
1      Ahmed                                   CS      2   Sir Khalid       B
2       Sara                       Cyber Security      3    Prof Abid       C
3       Sana                   Intelligent System      4  Prof Shahid       A
4       Saba               Electrical Engineering      5    Prof Asia       F
5    Daniyal               Mechanical Engineering      6   Prof Iqbal       C
6      Saima                    Civil Engineering      7      Sir Ali       G
7    Shabnam  Emerging Allied Health Technologies      8    Mam Nimra       A
8      Faria     Health Professional Technologies      9    Sir Moeez       B
9      Badar                            Chemistry     10    Mam Hifza       D
10     Lubna                              Physics     11    Mam Fizza       A
11  Shamraiz                            Economics     12   Mam Mennal       C
12   Fareeha                            Audiology     13   Mam Shazia       I
13    Sumbal                            Optometry     14   Mam Ayesha       B
0        NaN                                  NaN    NaN          NaN     NaN
1        NaN                                  NaN    NaN          NaN     NaN
2        NaN                                  NaN    NaN          NaN     NaN

                           degree      father_name phone_number  \
0                            BSAI  Muhammad Ashraf  03001234567
1                            BSCS   Muhammad Iqbal  03011234567
2               BS Cyber Security     Abdul Rehman  03021234567
3          BS Intelligent Systems    Muhammad Arif  03031234567
4       BS Electrical Engineering  Muhammad Yousaf  03041234567
5       BS Mechanical Engineering   Ghulam Mustafa  03051234567
6            BS Civil Engineering   Muhammad Aslam  03061234567
7   BS Allied Health Technologies   Muhammad Akram  03071234567
8          BS Health Technologies   Muhammad Hanif  03081234567
9                    BS Chemistry   Muhammad Rafiq  03091234567
10                     BS Physics     Abdul Sattar  03101234567
11                   BS Economics  Muhammad Bashir  03111234567
12                   BS Audiology   Muhammad Tariq  03121234567
13                   BS Optometry  Muhammad Saleem  03131234567
0                             NaN              NaN          NaN
1                             NaN              NaN          NaN
2                             NaN              NaN          NaN

               cnic  cgpa disability   name   age
0   35202-1234567-1  2.45       None    NaN   NaN
1   35202-2345678-2  2.78       None    NaN   NaN
2   35202-3456789-3  3.10   Physical    NaN   NaN
3   35202-4567890-4  3.25       None    NaN   NaN
4   35202-5678901-5  3.40     Visual    NaN   NaN
5   35202-6789012-6  3.55       None    NaN   NaN
6   35202-7890123-7  3.68    Hearing    NaN   NaN
7   35202-8901234-8  3.72       None    NaN   NaN
8   35202-9012345-9  3.80       None    NaN   NaN
9   35202-1122334-0  3.91   Physical    NaN   NaN
10  35202-2233445-1  2.95       None    NaN   NaN
11  35202-3344556-2  3.15     Visual    NaN   NaN
12  35202-4455667-3  3.50       None    NaN   NaN
13  35202-5566778-4  3.99       None    NaN   NaN
0               NaN   NaN        NaN  fizza  19.0
1               NaN   NaN        NaN  bilal   NaN
2               NaN   NaN        NaN   None  24.0

In [ ]:
e= pd.DataFrame({"degree":["cs","ai"]})
y= pd.DataFrame({"degree":["it","hr"]})

result = pd.concat([e,y])
print(result)

  degree
0     cs
1     ai
0     it
1     hr

In [ ]:
df4 = pd.DataFrame({"name":["fizza","bilal","abdullah","maan"],"age":[23,25,17,14],"marks":[23,45,67,36]})
df2 = pd.DataFrame({"name":["fizza","bilal","abdullah","maan"],"salary":[34000,390000,100000,20000]})
result = pd.merge(df4,df2)
print(result)

       name  age  marks  salary
0     fizza   23     23   34000
1     bilal   25     45  390000
2  abdullah   17     67  100000
3      maan   14     36   20000

In [ ]:
df4 = pd.DataFrame({"name":["fizza","bilal","abdullah","maan"],"age":[23,25,17,14],"Marks":[23,45,67,36]})

df4["new_Marks"] = df4["Marks"].apply(lambda x : x + 5)
print(df4)

       name  age  Marks  new_Marks
0     fizza   23     23         28
1     bilal   25     45         50
2  abdullah   17     67         72
3      maan   14     36         41